 artifacts_root : artifacts

 data_ingestion:
  root_dir: artifacts/data_project
  source_URL: https://github.com/ashish-kansagara/data/raw/refs/heads/main/wineQT.zip
  local_data_file: artifacts/data_project/data_wineQT.zip
  unzip_dir: artifacts/data_project